# Version catalog for aoc-2025-in-kotlin

[versions]
kotlin = "2.3.10"
kotlin-logging = "7.0.14"
logback = "1.5.31"

# Testing versions
junit-bom = "6.0.3"
kotest = "6.1.3"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

[libraries]
kotlin-logging = { group = "io.github.oshai", name = "kotlin-logging-jvm", version.ref = "kotlin-logging" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }

# JUnit libraries
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit-bom" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }

# Kotest assertions
kotest-assertions-core = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
