# Version catalog for aoc-2025-in-kotlin

[versions]
kotlin = "2.3.0-RC2"
kotlin-logging = "7.0.3"
logback = "1.5.21"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

[libraries]
kotlin-logging = { group = "io.github.oshai", name = "kotlin-logging-jvm", version.ref = "kotlin-logging" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }
